name: Terraform Apply
on:
  push:
    branches:
      - main
jobs:
  run-terraform-apply:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.3.0
        with:
          aqua_version: v2.25.1

      - name: Login to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: 'projects/73344241202/locations/global/workloadIdentityPools/default/providers/provider-github'
          service_account: 'gh-actions@terraform-cloudrun-attack.iam.gserviceaccount.com'

      - name: Terraform Init
        run: terraform init

      - name: TFlint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tflint --config .tflint.hcl --init
          tflint --config .tflint.hcl --format=checkstyle | \
          reviewdog -f=checkstyle \
                    -name="tflint" \
                    -reporter=github-pr-review \
                    -filter-mode=nofilter \
                    -fail-on-error

      - name: Check terraform fmt
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt apply -- terraform apply -auto-approve
